import assert from'node:assert/strict';import{AVS_AUDIO_SAMPLES,AVS_CHANNEL_SHIFT_APE_ID,AVS_COLOR_REDUCTION_APE_ID,AVS_MULTIPLIER_APE_ID,AvsCompatibilityRuntime,type AvsAudioFrame,type AvsComponent,type AvsPresetAst}from'../src/avs/index.ts';import{buildExactAvsPointwiseWgsl,type ExactAvsPointwiseOperation}from'../src/avs/gpu-frame-graph.ts';import{createExactGpuChannelShiftResolver,planTerminalExactGpuPasses}from'../src/avs/gpu-preset-plan.ts';
import{buildExactAvsConvolutionWgsl}from'../src/avs/effects/convolution-gpu.ts';
let assertions=0;const check=(value:unknown,message:string):asserts value=>{assertions++;assert.ok(value,message);},source=randomPixels(65_537,0x41504547);
for(const mode of[1183,1020,1018,1022,1019,1021,1023]){const fixture=ape(AVS_CHANNEL_SHIFT_APE_ID,channelPayload(mode,false),'0'),operation=single(fixture);check(operation.kind==='channel-shift'&&operation.mode===mode,`Channel Shift ${mode} config`);compare(fixture,operation,source,`Channel Shift ${mode}`);}
for(const levels of[0,1,2,7,8,12,-3]){const fixture=ape(AVS_COLOR_REDUCTION_APE_ID,reductionPayload(levels),'0'),operation=single(fixture);check(operation.kind==='color-reduction',`Color Reduction ${levels} config`);compare(fixture,operation,source,`Color Reduction ${levels}`);}
const malformedReduction=ape(AVS_COLOR_REDUCTION_APE_ID,new Uint8Array(4),'0');compare(malformedReduction,single(malformedReduction),source,'Color Reduction malformed');
for(const mode of[-1,0,1,2,3,4,5,6,7,8])for(const length of[16,17]){const fixture=ape(AVS_MULTIPLIER_APE_ID,i32(mode),'0'),operation=single(fixture);check(operation.kind==='multiplier'&&operation.mode===mode,`Multiplier ${mode} config`);compare(fixture,operation,source.subarray(0,length),`Multiplier ${mode} length ${length}`);}
const fusedFixtures=[ape(AVS_CHANNEL_SHIFT_APE_ID,channelPayload(1018,false),'0'),ape(AVS_COLOR_REDUCTION_APE_ID,reductionPayload(4),'1'),ape(AVS_MULTIPLIER_APE_ID,i32(3),'2')],fused=planTerminalExactGpuPasses(preset(fusedFixtures));check(fused.passes.length===1&&fused.fusedPointwiseOperations===3,'three APEs fuse to one pass');const operations=(fused.passes[0]as{kind:'pointwise';operations:readonly ExactAvsPointwiseOperation[]}).operations;let actual=new Uint32Array(source);for(const operation of operations)actual=emulate(actual,operation);assert.deepEqual(actual,cpu(fusedFixtures,source),'fused APE sequence');assertions++;
const randomComponent=ape(AVS_CHANNEL_SHIFT_APE_ID,channelPayload(1020,true),'random/path'),randomPlan=planTerminalExactGpuPasses(preset([randomComponent]));check(randomPlan.passes.length===0,'beat-random immutable suffix fails closed');const resolver=createExactGpuChannelShiftResolver(randomComponent),runtime=new AvsCompatibilityRuntime(preset([randomComponent],false),19,1),beats=[false,true,false,true,true,false];for(let frame=0;frame<beats.length;frame++){const input=randomPixels(19,0x12345678+frame);runtime.framebuffer.pixels.set(input);const expected=new Uint32Array(runtime.render(audio(beats[frame]!)).framebuffer.pixels),resolved=resolver.resolve(beats[frame]!);assert.deepEqual(emulate(input,resolved),expected,`beat-random Channel Shift frame ${frame}`);assertions++;}
for(const operation of[...operations,resolver.resolve(false)]){const shader=buildExactAvsPointwiseWgsl([operation]);check(!/textureSample|sampler|\bf32\b/.test(shader),`${operation.kind} integer-only shader`);check(shader.includes('index'),`${operation.kind} shader has pixel index`);}
const kernel=Array(49).fill(0);kernel[0]=1;const convolutionShader=buildExactAvsConvolutionWgsl({enabled:true,wrap:false,absolute:false,twoPass:false,kernel,bias:0,scale:1,legacyFilename:''},17,11,false,operations);check(convolutionShader.includes('let index = global.y * WIDTH + global.x;'),'convolution fusion exposes global pixel index');check(convolutionShader.includes('if (index >= 4u)'),'convolution fusion accepts index-aware APEs');
console.log(`avs-pointwise-ape-gpu-check: PASS (${assertions} assertions)`);
function single(component:AvsComponent):ExactAvsPointwiseOperation{const plan=planTerminalExactGpuPasses(preset([component]));check(plan.extractedComponents===1,`${component.apeId} extracted`);const pass=plan.passes[0];check(pass?.kind==='pointwise',`${component.apeId} pointwise pass`);return(pass as{kind:'pointwise';operations:readonly ExactAvsPointwiseOperation[]}).operations[0]!;}
function compare(component:AvsComponent,operation:ExactAvsPointwiseOperation,pixels:Uint32Array,label:string):void{assert.deepEqual(emulate(pixels,operation),cpu([component],pixels),label);assertions++;}
function emulate(input:Uint32Array,operation:ExactAvsPointwiseOperation):Uint32Array{const output=new Uint32Array(input);for(let index=0;index<output.length;index++){let pixel=output[index]!&0xffffff,low=pixel&255,middle=(pixel>>>8)&255,high=(pixel>>>16)&255,pack=(l:number,m:number,h:number)=>l|(m<<8)|(h<<16);switch(operation.kind){case'channel-shift':pixel=operation.mode===1020?pack(middle,low,high):operation.mode===1018?pack(high,low,middle):operation.mode===1022?pack(low,high,middle):operation.mode===1019?pack(middle,high,low):operation.mode===1021?pack(high,middle,low):pixel;break;case'color-reduction':if(index>=4)pixel&=operation.mask;break;case'multiplier':if(operation.mode===0&&index>0)pixel=pixel===0?0:0xffffff;else if(operation.mode===7&&index>0)pixel=pixel===0xffffff?0xffffff:0;else if(operation.mode>=1&&operation.mode<=6&&index<output.length-(output.length&1)){if(operation.mode<=3){const factor=1<<(4-operation.mode);pixel=pack(Math.min(255,low*factor),Math.min(255,middle*factor),Math.min(255,high*factor));}else{const shift=operation.mode-3;pixel=pack(low>>>shift,middle>>>shift,high>>>shift);}}break;default:throw new Error(`unexpected ${operation.kind}`);}output[index]=pixel;}return output;}
function cpu(components:readonly AvsComponent[],pixels:Uint32Array):Uint32Array{const runtime=new AvsCompatibilityRuntime(preset(components,false),pixels.length,1);runtime.framebuffer.pixels.set(pixels);return new Uint32Array(runtime.render(audio(false)).framebuffer.pixels);}
function ape(apeId:string,payload:Uint8Array,path:string):AvsComponent{return{effectId:16384,apeId,payload,fileOffset:0,path,children:[],list:null,listCode:null};}function preset(components:readonly AvsComponent[],clearEveryFrame=true):AvsPresetAst{return{version:2,header:'test',clearEveryFrame,components,byteLength:0};}function channelPayload(mode:number,random:boolean):Uint8Array{const payload=new Uint8Array(8),view=new DataView(payload.buffer);view.setInt32(0,mode,true);view.setInt32(4,random?1:0,true);return payload;}function reductionPayload(levels:number):Uint8Array{const payload=new Uint8Array(264);new DataView(payload.buffer).setInt32(260,levels,true);return payload;}function i32(value:number):Uint8Array{const payload=new Uint8Array(4);new DataView(payload.buffer).setInt32(0,value,true);return payload;}function randomPixels(length:number,seed:number):Uint32Array{let state=seed>>>0,out=new Uint32Array(length);for(let i=0;i<length;i++){state^=state<<13;state^=state>>>17;state^=state<<5;out[i]=state&0xffffff;}return out;}function audio(beat:boolean):AvsAudioFrame{return{waveform:[new Uint8Array(AVS_AUDIO_SAMPLES),new Uint8Array(AVS_AUDIO_SAMPLES)],spectrum:[new Uint8Array(AVS_AUDIO_SAMPLES),new Uint8Array(AVS_AUDIO_SAMPLES)],beat,beatLevel:0};}
