import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { AVS_TEXER_APE_ID, AVS_TEXER_II_APE_ID, decodeAvsTexer2Config, decodeAvsTexerConfig, parseAvsPreset, planAvsOrderedTileBinning, type AvsComponent } from '../src/avs/index.ts';
const width=640,height=360;
const corpora=[{id:'bundled',paths:[resolve('assets/avs-presets/community-picks'),resolve('assets/avs-presets/winamp-5-picks')]},{id:'private',paths:[resolve('avs presets/presets/unique')]}];
const output:Record<string,unknown>={frame:{width,height},definition:'fixed-size raster eligibility; bitmap resolution and record generation remain integration dependencies'};
for(const corpus of corpora){let parsed=0,failed=0,instances=0,eligible=0,targetPresets=0;const kinds:Record<string,{instances:number;eligible:number}>={};const reasons:Record<string,number>={};for(const file of corpus.paths.flatMap(files)){try{const preset=parseAvsPreset(new Uint8Array(readFileSync(file)));parsed++;let target=false;visit(preset.components,c=>{let kind:string|undefined,capacity=0,reason:string|undefined;if(c.apeId===AVS_TEXER_APE_ID){kind='texer';const p=decodeAvsTexerConfig(c.payload).particles;capacity=Math.min(width*height,Math.max(1,p));}else if(c.apeId===AVS_TEXER_II_APE_ID){kind='texer-ii';const config=decodeAvsTexer2Config(c.payload);if(config.resize)reason='resized';else capacity=65_536*(config.wrap?4:1);}if(!kind)return;target=true;instances++;const row=kinds[kind]??={instances:0,eligible:0};row.instances++;if(!reason){const plan=planAvsOrderedTileBinning(width,height,capacity,{tileSizes:[16]});if(!plan.eligible)reason=plan.reason??'plan';}if(reason)reasons[reason]=(reasons[reason]??0)+1;else{eligible++;row.eligible++;}});if(target)targetPresets++;}catch{failed++;}}output[corpus.id]={files:corpus.paths.flatMap(files).length,parsed,failed,targetPresets,instances,eligible,eligibilityPercent:instances?eligible/instances*100:100,kinds,reasons};}
console.log(JSON.stringify(output,null,2));
function visit(cs:readonly AvsComponent[],fn:(c:AvsComponent)=>void):void{for(const c of cs){fn(c);visit(c.children,fn);}}
function files(dir:string):string[]{const out:string[]=[];for(const e of readdirSync(dir,{withFileTypes:true})){const p=resolve(dir,e.name);if(e.isDirectory())out.push(...files(p));else if(e.isFile()&&e.name.toLowerCase().endsWith('.avs'))out.push(p);}return out;}
