// Generated by tools/generate-bundled-avs-presets.mjs. Do not hand-edit.
import preset000 from "../../assets/avs-presets/community-picks/Acid - Twitchy liquid shit (mixing plastics mix by tuggummi).avs";
import preset001 from "../../assets/avs-presets/community-picks/amphirion - Ex Deux Mechanica.avs";
import preset002 from "../../assets/avs-presets/community-picks/Amphirion - Geometric Sustinance.avs";
import preset003 from "../../assets/avs-presets/community-picks/Degnic - Data flow.avs";
import preset004 from "../../assets/avs-presets/community-picks/Degnic - Fractal (slo-mo metallic) (u).avs";
import preset005 from "../../assets/avs-presets/community-picks/Degnic - Fury (extreme remix) by fsk.avs";
import preset006 from "../../assets/avs-presets/community-picks/Degnic - Helium.avs";
import preset007 from "../../assets/avs-presets/community-picks/degnic - spirit realm (plasmoid rmx).avs";
import preset008 from "../../assets/avs-presets/community-picks/duo - alien intercourse 4.avs";
import preset009 from "../../assets/avs-presets/community-picks/duo - Alienated (evilrice trinity tron remix).avs";
import preset010 from "../../assets/avs-presets/community-picks/Duo - Hash the Planet.avs";
import preset011 from "../../assets/avs-presets/community-picks/duo - warm freeform.avs";
import preset012 from "../../assets/avs-presets/community-picks/el-vis - golden.avs";
import preset013 from "../../assets/avs-presets/community-picks/el-vis - hubble002.avs";
import preset014 from "../../assets/avs-presets/community-picks/el-vis - rittaufdemfeuerstrahl.avs";
import preset015 from "../../assets/avs-presets/community-picks/el-vis - spindle.avs";
import preset016 from "../../assets/avs-presets/community-picks/fUk - afterburner remix.avs";
import preset017 from "../../assets/avs-presets/community-picks/fUk - cube.avs";
import preset018 from "../../assets/avs-presets/community-picks/fUk - ice cube.avs";
import preset019 from "../../assets/avs-presets/community-picks/Jay-Fatboy - Pieces of a Dead world.avs";
import preset020 from "../../assets/avs-presets/community-picks/Jheriko - Alien Device (Gallery Remix by Zamuz).avs";
import preset021 from "../../assets/avs-presets/community-picks/NemoOrange - Building Blocks.avs";
import preset022 from "../../assets/avs-presets/community-picks/NemoOrange - Clockwork.avs";
import preset023 from "../../assets/avs-presets/community-picks/NemoOrange - the Light of Speed.avs";
import preset024 from "../../assets/avs-presets/community-picks/NemoOrange vs el-vis - dreamtime2.avs";
import preset025 from "../../assets/avs-presets/community-picks/S_KuPeRS - Curvism 002 (Tuggummi's Paprika Mix).avs";
import preset026 from "../../assets/avs-presets/community-picks/s_kupers - gace.avs";
import preset027 from "../../assets/avs-presets/community-picks/s_kupers - the revenge of mt. doom.avs";
import preset028 from "../../assets/avs-presets/community-picks/Shock Value - Architectural Design (v.1.01).avs";
import preset029 from "../../assets/avs-presets/community-picks/shock value - source of power.avs";
import preset030 from "../../assets/avs-presets/community-picks/Tonic - One More (BW Contest).avs";
import preset031 from "../../assets/avs-presets/community-picks/Tonic - Zoomed Picture from One Insect.avs";
import preset032 from "../../assets/avs-presets/community-picks/Tuggummi - Let me out!.avs";
import preset033 from "../../assets/avs-presets/community-picks/Tuggummi - Shiny metal curves.avs";
import preset034 from "../../assets/avs-presets/community-picks/UnConeD - Butterfly Caught.avs";
import preset035 from "../../assets/avs-presets/community-picks/UnConeD - Daedalus.avs";
import preset036 from "../../assets/avs-presets/community-picks/UnConeD - Don't Trip and Drive.avs";
import preset037 from "../../assets/avs-presets/community-picks/UnConeD - Goldie.avs";
import preset038 from "../../assets/avs-presets/community-picks/UnConeD - Mister Santa.avs";
import preset039 from "../../assets/avs-presets/community-picks/UnConeD - Seismogrid.avs";
import preset040 from "../../assets/avs-presets/community-picks/UnConeD - Silk Strings.avs";
import preset041 from "../../assets/avs-presets/community-picks/UnConeD - Tokyo Bullet.avs";
import preset042 from "../../assets/avs-presets/community-picks/yathosho - interlaced.avs";
import preset043 from "../../assets/avs-presets/community-picks/yathosho - sakura.avs";
import preset044 from "../../assets/avs-presets/community-picks/Yathosho - SKOGSKLOCKA(TM).avs";
import preset045 from "../../assets/avs-presets/community-picks/zamuz - big bang.avs";
import preset046 from "../../assets/avs-presets/community-picks/Zamuz - Explosive Virus.avs";
import preset047 from "../../assets/avs-presets/community-picks/zamuz - spiritual.avs";
import preset048 from "../../assets/avs-presets/community-picks/zamuz meets tuggummi - fat balls (wallpaper wannabe candy theme).avs";
import preset049 from "../../assets/avs-presets/community-picks/Zevensoft - Ocean4.avs";
import preset050 from "../../assets/avs-presets/winamp-5-picks/amphirion - nebulous (skupers remix).avs";
import preset051 from "../../assets/avs-presets/winamp-5-picks/D&L - Life Is Violated.avs";
import preset052 from "../../assets/avs-presets/winamp-5-picks/Degnic - Retrowall (Yathosho's Supermicrocosm).avs";
import preset053 from "../../assets/avs-presets/winamp-5-picks/Degnic-Adrealine rush.avs";
import preset054 from "../../assets/avs-presets/winamp-5-picks/Duo - Alien Heart.avs";
import preset055 from "../../assets/avs-presets/winamp-5-picks/Duo - Brainstorm.avs";
import preset056 from "../../assets/avs-presets/winamp-5-picks/EL-VIS - Molecules (S_KuPeRS Remix).avs";
import preset057 from "../../assets/avs-presets/winamp-5-picks/el-vis - soundscape III (skupers remix).avs";
import preset058 from "../../assets/avs-presets/winamp-5-picks/fck - checkers with metaballs (skupers remix).avs";
import preset059 from "../../assets/avs-presets/winamp-5-picks/horse-fly - jinx (skupers remix).avs";
import preset060 from "../../assets/avs-presets/winamp-5-picks/jheriko - not quite a bendy tunnel (skupers remix).avs";
import preset061 from "../../assets/avs-presets/winamp-5-picks/justin - newpoop (for wa5).avs";
import preset062 from "../../assets/avs-presets/winamp-5-picks/justin - the landscape is killing me (wa5remix).avs";
import preset063 from "../../assets/avs-presets/winamp-5-picks/L1quid - Take the Veil.avs";
import preset064 from "../../assets/avs-presets/winamp-5-picks/mig - Dragonscales.avs";
import preset065 from "../../assets/avs-presets/winamp-5-picks/mig - Encapsulade.avs";
import preset066 from "../../assets/avs-presets/winamp-5-picks/mig - Freekwyrms.avs";
import preset067 from "../../assets/avs-presets/winamp-5-picks/mig - Lilypod.avs";
import preset068 from "../../assets/avs-presets/winamp-5-picks/mig - Mist Wisps.avs";
import preset069 from "../../assets/avs-presets/winamp-5-picks/mig - Nebulating - Hypercolorspace.avs";
import preset070 from "../../assets/avs-presets/winamp-5-picks/mig - Reverb - Deep Net.avs";
import preset071 from "../../assets/avs-presets/winamp-5-picks/mig - Slyde - Tri.avs";
import preset072 from "../../assets/avs-presets/winamp-5-picks/mig - Solar Flaire.avs";
import preset073 from "../../assets/avs-presets/winamp-5-picks/mig - Spintronics - Backspin.avs";
import preset074 from "../../assets/avs-presets/winamp-5-picks/mig - Starslappin.avs";
import preset075 from "../../assets/avs-presets/winamp-5-picks/mig - Street Art - Fire Inside.avs";
import preset076 from "../../assets/avs-presets/winamp-5-picks/mig - Swoo - Slow.avs";
import preset077 from "../../assets/avs-presets/winamp-5-picks/Nic01 - Rototronik.avs";
import preset078 from "../../assets/avs-presets/winamp-5-picks/nixa - smell of music (skupers remix).avs";
import preset079 from "../../assets/avs-presets/winamp-5-picks/p-k - bumpy.avs";
import preset080 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - ...hidden track....avs";
import preset081 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - A Tribute To Degnic.avs";
import preset082 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Arctic Rainbow.avs";
import preset083 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Chinook.avs";
import preset084 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - female demands.avs";
import preset085 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Hexual Healing.avs";
import preset086 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Inverse Kinetics.avs";
import preset087 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Kingish.avs";
import preset088 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Spirit Realm (Degnic's Plasmoid RMX).avs";
import preset089 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Texering 002.avs";
import preset090 from "../../assets/avs-presets/winamp-5-picks/S_KuPeRS - Upward Current.avs";
import preset091 from "../../assets/avs-presets/winamp-5-picks/skupers - chinook (exclusive version).avs";
import preset092 from "../../assets/avs-presets/winamp-5-picks/splendora.avs";
import preset093 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Aqua-fumes.avs";
import preset094 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Club Seizure (color enhanced mix).avs";
import preset095 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Different Load.avs";
import preset096 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Electro blobs.avs";
import preset097 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Kaleidofied.avs";
import preset098 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Magma Flow II.avs";
import preset099 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Multiple Orgasms.avs";
import preset100 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Odour Control.avs";
import preset101 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Pina Colada.avs";
import preset102 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Scope in Spotlight II.avs";
import preset103 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Solero Shots.avs";
import preset104 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Square Minded.avs";
import preset105 from "../../assets/avs-presets/winamp-5-picks/Tuggummi - Worm-O-Rama (Raz Remix).avs";
import preset106 from "../../assets/avs-presets/winamp-5-picks/UnConeD -  Zero-G Maze.avs";
import preset107 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Cartoon Trip.avs";
import preset108 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Containment.avs";
import preset109 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Cubic Flower.avs";
import preset110 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Jello Cube.avs";
import preset111 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Mercury.avs";
import preset112 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Neon Coaster.avs";
import preset113 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Plankton.avs";
import preset114 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Reflectocube.avs";
import preset115 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Speeder 3K.avs";
import preset116 from "../../assets/avs-presets/winamp-5-picks/UnConeD - TC Plasma.avs";
import preset117 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Tie Tunnel SSC.avs";
import preset118 from "../../assets/avs-presets/winamp-5-picks/UnConeD - Zero-G Maze II.avs";
import preset119 from "../../assets/avs-presets/winamp-5-picks/UnConeD -Retrosquares.avs";
import preset120 from "../../assets/avs-presets/winamp-5-picks/UnConeD -Zero-G Maze III.avs";
import preset121 from "../../assets/avs-presets/winamp-5-picks/yathosho - fabric (skupers remix).avs";
import preset122 from "../../assets/avs-presets/winamp-5-picks/Yathosho - microcosm 02.avs";
import preset123 from "../../assets/avs-presets/winamp-5-picks/zxe-Urantia.avs";

export const BUNDLED_AVS_PRESET_CATALOG = [
  { id: "community-picks/Acid - Twitchy liquid shit (mixing plastics mix by tuggummi)", name: "Acid - Twitchy liquid shit (mixing plastics mix by tuggummi)", fileName: "Acid - Twitchy liquid shit (mixing plastics mix by tuggummi).avs", collection: "Community Picks", url: preset000 },
  { id: "community-picks/amphirion - Ex Deux Mechanica", name: "amphirion - Ex Deux Mechanica", fileName: "amphirion - Ex Deux Mechanica.avs", collection: "Community Picks", url: preset001 },
  { id: "community-picks/Amphirion - Geometric Sustinance", name: "Amphirion - Geometric Sustinance", fileName: "Amphirion - Geometric Sustinance.avs", collection: "Community Picks", url: preset002 },
  { id: "community-picks/Degnic - Data flow", name: "Degnic - Data flow", fileName: "Degnic - Data flow.avs", collection: "Community Picks", url: preset003 },
  { id: "community-picks/Degnic - Fractal (slo-mo metallic) (u)", name: "Degnic - Fractal (slo-mo metallic) (u)", fileName: "Degnic - Fractal (slo-mo metallic) (u).avs", collection: "Community Picks", url: preset004 },
  { id: "community-picks/Degnic - Fury (extreme remix) by fsk", name: "Degnic - Fury (extreme remix) by fsk", fileName: "Degnic - Fury (extreme remix) by fsk.avs", collection: "Community Picks", url: preset005 },
  { id: "community-picks/Degnic - Helium", name: "Degnic - Helium", fileName: "Degnic - Helium.avs", collection: "Community Picks", url: preset006 },
  { id: "community-picks/degnic - spirit realm (plasmoid rmx)", name: "degnic - spirit realm (plasmoid rmx)", fileName: "degnic - spirit realm (plasmoid rmx).avs", collection: "Community Picks", url: preset007 },
  { id: "community-picks/duo - alien intercourse 4", name: "duo - alien intercourse 4", fileName: "duo - alien intercourse 4.avs", collection: "Community Picks", url: preset008 },
  { id: "community-picks/duo - Alienated (evilrice trinity tron remix)", name: "duo - Alienated (evilrice trinity tron remix)", fileName: "duo - Alienated (evilrice trinity tron remix).avs", collection: "Community Picks", url: preset009 },
  { id: "community-picks/Duo - Hash the Planet", name: "Duo - Hash the Planet", fileName: "Duo - Hash the Planet.avs", collection: "Community Picks", url: preset010 },
  { id: "community-picks/duo - warm freeform", name: "duo - warm freeform", fileName: "duo - warm freeform.avs", collection: "Community Picks", url: preset011 },
  { id: "community-picks/el-vis - golden", name: "el-vis - golden", fileName: "el-vis - golden.avs", collection: "Community Picks", url: preset012 },
  { id: "community-picks/el-vis - hubble002", name: "el-vis - hubble002", fileName: "el-vis - hubble002.avs", collection: "Community Picks", url: preset013 },
  { id: "community-picks/el-vis - rittaufdemfeuerstrahl", name: "el-vis - rittaufdemfeuerstrahl", fileName: "el-vis - rittaufdemfeuerstrahl.avs", collection: "Community Picks", url: preset014 },
  { id: "community-picks/el-vis - spindle", name: "el-vis - spindle", fileName: "el-vis - spindle.avs", collection: "Community Picks", url: preset015 },
  { id: "community-picks/fUk - afterburner remix", name: "fUk - afterburner remix", fileName: "fUk - afterburner remix.avs", collection: "Community Picks", url: preset016 },
  { id: "community-picks/fUk - cube", name: "fUk - cube", fileName: "fUk - cube.avs", collection: "Community Picks", url: preset017 },
  { id: "community-picks/fUk - ice cube", name: "fUk - ice cube", fileName: "fUk - ice cube.avs", collection: "Community Picks", url: preset018 },
  { id: "community-picks/Jay-Fatboy - Pieces of a Dead world", name: "Jay-Fatboy - Pieces of a Dead world", fileName: "Jay-Fatboy - Pieces of a Dead world.avs", collection: "Community Picks", url: preset019 },
  { id: "community-picks/Jheriko - Alien Device (Gallery Remix by Zamuz)", name: "Jheriko - Alien Device (Gallery Remix by Zamuz)", fileName: "Jheriko - Alien Device (Gallery Remix by Zamuz).avs", collection: "Community Picks", url: preset020 },
  { id: "community-picks/NemoOrange - Building Blocks", name: "NemoOrange - Building Blocks", fileName: "NemoOrange - Building Blocks.avs", collection: "Community Picks", url: preset021 },
  { id: "community-picks/NemoOrange - Clockwork", name: "NemoOrange - Clockwork", fileName: "NemoOrange - Clockwork.avs", collection: "Community Picks", url: preset022 },
  { id: "community-picks/NemoOrange - the Light of Speed", name: "NemoOrange - the Light of Speed", fileName: "NemoOrange - the Light of Speed.avs", collection: "Community Picks", url: preset023 },
  { id: "community-picks/NemoOrange vs el-vis - dreamtime2", name: "NemoOrange vs el-vis - dreamtime2", fileName: "NemoOrange vs el-vis - dreamtime2.avs", collection: "Community Picks", url: preset024 },
  { id: "community-picks/S_KuPeRS - Curvism 002 (Tuggummi's Paprika Mix)", name: "S_KuPeRS - Curvism 002 (Tuggummi's Paprika Mix)", fileName: "S_KuPeRS - Curvism 002 (Tuggummi's Paprika Mix).avs", collection: "Community Picks", url: preset025 },
  { id: "community-picks/s_kupers - gace", name: "s_kupers - gace", fileName: "s_kupers - gace.avs", collection: "Community Picks", url: preset026 },
  { id: "community-picks/s_kupers - the revenge of mt. doom", name: "s_kupers - the revenge of mt. doom", fileName: "s_kupers - the revenge of mt. doom.avs", collection: "Community Picks", url: preset027 },
  { id: "community-picks/Shock Value - Architectural Design (v.1.01)", name: "Shock Value - Architectural Design (v.1.01)", fileName: "Shock Value - Architectural Design (v.1.01).avs", collection: "Community Picks", url: preset028 },
  { id: "community-picks/shock value - source of power", name: "shock value - source of power", fileName: "shock value - source of power.avs", collection: "Community Picks", url: preset029 },
  { id: "community-picks/Tonic - One More (BW Contest)", name: "Tonic - One More (BW Contest)", fileName: "Tonic - One More (BW Contest).avs", collection: "Community Picks", url: preset030 },
  { id: "community-picks/Tonic - Zoomed Picture from One Insect", name: "Tonic - Zoomed Picture from One Insect", fileName: "Tonic - Zoomed Picture from One Insect.avs", collection: "Community Picks", url: preset031 },
  { id: "community-picks/Tuggummi - Let me out!", name: "Tuggummi - Let me out!", fileName: "Tuggummi - Let me out!.avs", collection: "Community Picks", url: preset032 },
  { id: "community-picks/Tuggummi - Shiny metal curves", name: "Tuggummi - Shiny metal curves", fileName: "Tuggummi - Shiny metal curves.avs", collection: "Community Picks", url: preset033 },
  { id: "community-picks/UnConeD - Butterfly Caught", name: "UnConeD - Butterfly Caught", fileName: "UnConeD - Butterfly Caught.avs", collection: "Community Picks", url: preset034 },
  { id: "community-picks/UnConeD - Daedalus", name: "UnConeD - Daedalus", fileName: "UnConeD - Daedalus.avs", collection: "Community Picks", url: preset035 },
  { id: "community-picks/UnConeD - Don't Trip and Drive", name: "UnConeD - Don't Trip and Drive", fileName: "UnConeD - Don't Trip and Drive.avs", collection: "Community Picks", url: preset036 },
  { id: "community-picks/UnConeD - Goldie", name: "UnConeD - Goldie", fileName: "UnConeD - Goldie.avs", collection: "Community Picks", url: preset037 },
  { id: "community-picks/UnConeD - Mister Santa", name: "UnConeD - Mister Santa", fileName: "UnConeD - Mister Santa.avs", collection: "Community Picks", url: preset038 },
  { id: "community-picks/UnConeD - Seismogrid", name: "UnConeD - Seismogrid", fileName: "UnConeD - Seismogrid.avs", collection: "Community Picks", url: preset039 },
  { id: "community-picks/UnConeD - Silk Strings", name: "UnConeD - Silk Strings", fileName: "UnConeD - Silk Strings.avs", collection: "Community Picks", url: preset040 },
  { id: "community-picks/UnConeD - Tokyo Bullet", name: "UnConeD - Tokyo Bullet", fileName: "UnConeD - Tokyo Bullet.avs", collection: "Community Picks", url: preset041 },
  { id: "community-picks/yathosho - interlaced", name: "yathosho - interlaced", fileName: "yathosho - interlaced.avs", collection: "Community Picks", url: preset042 },
  { id: "community-picks/yathosho - sakura", name: "yathosho - sakura", fileName: "yathosho - sakura.avs", collection: "Community Picks", url: preset043 },
  { id: "community-picks/Yathosho - SKOGSKLOCKA(TM)", name: "Yathosho - SKOGSKLOCKA(TM)", fileName: "Yathosho - SKOGSKLOCKA(TM).avs", collection: "Community Picks", url: preset044 },
  { id: "community-picks/zamuz - big bang", name: "zamuz - big bang", fileName: "zamuz - big bang.avs", collection: "Community Picks", url: preset045 },
  { id: "community-picks/Zamuz - Explosive Virus", name: "Zamuz - Explosive Virus", fileName: "Zamuz - Explosive Virus.avs", collection: "Community Picks", url: preset046 },
  { id: "community-picks/zamuz - spiritual", name: "zamuz - spiritual", fileName: "zamuz - spiritual.avs", collection: "Community Picks", url: preset047 },
  { id: "community-picks/zamuz meets tuggummi - fat balls (wallpaper wannabe candy theme)", name: "zamuz meets tuggummi - fat balls (wallpaper wannabe candy theme)", fileName: "zamuz meets tuggummi - fat balls (wallpaper wannabe candy theme).avs", collection: "Community Picks", url: preset048 },
  { id: "community-picks/Zevensoft - Ocean4", name: "Zevensoft - Ocean4", fileName: "Zevensoft - Ocean4.avs", collection: "Community Picks", url: preset049 },
  { id: "winamp-5-picks/amphirion - nebulous (skupers remix)", name: "amphirion - nebulous (skupers remix)", fileName: "amphirion - nebulous (skupers remix).avs", collection: "Winamp 5 Picks", url: preset050 },
  { id: "winamp-5-picks/D&L - Life Is Violated", name: "D&L - Life Is Violated", fileName: "D&L - Life Is Violated.avs", collection: "Winamp 5 Picks", url: preset051 },
  { id: "winamp-5-picks/Degnic - Retrowall (Yathosho's Supermicrocosm)", name: "Degnic - Retrowall (Yathosho's Supermicrocosm)", fileName: "Degnic - Retrowall (Yathosho's Supermicrocosm).avs", collection: "Winamp 5 Picks", url: preset052 },
  { id: "winamp-5-picks/Degnic-Adrealine rush", name: "Degnic-Adrealine rush", fileName: "Degnic-Adrealine rush.avs", collection: "Winamp 5 Picks", url: preset053 },
  { id: "winamp-5-picks/Duo - Alien Heart", name: "Duo - Alien Heart", fileName: "Duo - Alien Heart.avs", collection: "Winamp 5 Picks", url: preset054 },
  { id: "winamp-5-picks/Duo - Brainstorm", name: "Duo - Brainstorm", fileName: "Duo - Brainstorm.avs", collection: "Winamp 5 Picks", url: preset055 },
  { id: "winamp-5-picks/EL-VIS - Molecules (S_KuPeRS Remix)", name: "EL-VIS - Molecules (S_KuPeRS Remix)", fileName: "EL-VIS - Molecules (S_KuPeRS Remix).avs", collection: "Winamp 5 Picks", url: preset056 },
  { id: "winamp-5-picks/el-vis - soundscape III (skupers remix)", name: "el-vis - soundscape III (skupers remix)", fileName: "el-vis - soundscape III (skupers remix).avs", collection: "Winamp 5 Picks", url: preset057 },
  { id: "winamp-5-picks/fck - checkers with metaballs (skupers remix)", name: "fck - checkers with metaballs (skupers remix)", fileName: "fck - checkers with metaballs (skupers remix).avs", collection: "Winamp 5 Picks", url: preset058 },
  { id: "winamp-5-picks/horse-fly - jinx (skupers remix)", name: "horse-fly - jinx (skupers remix)", fileName: "horse-fly - jinx (skupers remix).avs", collection: "Winamp 5 Picks", url: preset059 },
  { id: "winamp-5-picks/jheriko - not quite a bendy tunnel (skupers remix)", name: "jheriko - not quite a bendy tunnel (skupers remix)", fileName: "jheriko - not quite a bendy tunnel (skupers remix).avs", collection: "Winamp 5 Picks", url: preset060 },
  { id: "winamp-5-picks/justin - newpoop (for wa5)", name: "justin - newpoop (for wa5)", fileName: "justin - newpoop (for wa5).avs", collection: "Winamp 5 Picks", url: preset061 },
  { id: "winamp-5-picks/justin - the landscape is killing me (wa5remix)", name: "justin - the landscape is killing me (wa5remix)", fileName: "justin - the landscape is killing me (wa5remix).avs", collection: "Winamp 5 Picks", url: preset062 },
  { id: "winamp-5-picks/L1quid - Take the Veil", name: "L1quid - Take the Veil", fileName: "L1quid - Take the Veil.avs", collection: "Winamp 5 Picks", url: preset063 },
  { id: "winamp-5-picks/mig - Dragonscales", name: "mig - Dragonscales", fileName: "mig - Dragonscales.avs", collection: "Winamp 5 Picks", url: preset064 },
  { id: "winamp-5-picks/mig - Encapsulade", name: "mig - Encapsulade", fileName: "mig - Encapsulade.avs", collection: "Winamp 5 Picks", url: preset065 },
  { id: "winamp-5-picks/mig - Freekwyrms", name: "mig - Freekwyrms", fileName: "mig - Freekwyrms.avs", collection: "Winamp 5 Picks", url: preset066 },
  { id: "winamp-5-picks/mig - Lilypod", name: "mig - Lilypod", fileName: "mig - Lilypod.avs", collection: "Winamp 5 Picks", url: preset067 },
  { id: "winamp-5-picks/mig - Mist Wisps", name: "mig - Mist Wisps", fileName: "mig - Mist Wisps.avs", collection: "Winamp 5 Picks", url: preset068 },
  { id: "winamp-5-picks/mig - Nebulating - Hypercolorspace", name: "mig - Nebulating - Hypercolorspace", fileName: "mig - Nebulating - Hypercolorspace.avs", collection: "Winamp 5 Picks", url: preset069 },
  { id: "winamp-5-picks/mig - Reverb - Deep Net", name: "mig - Reverb - Deep Net", fileName: "mig - Reverb - Deep Net.avs", collection: "Winamp 5 Picks", url: preset070 },
  { id: "winamp-5-picks/mig - Slyde - Tri", name: "mig - Slyde - Tri", fileName: "mig - Slyde - Tri.avs", collection: "Winamp 5 Picks", url: preset071 },
  { id: "winamp-5-picks/mig - Solar Flaire", name: "mig - Solar Flaire", fileName: "mig - Solar Flaire.avs", collection: "Winamp 5 Picks", url: preset072 },
  { id: "winamp-5-picks/mig - Spintronics - Backspin", name: "mig - Spintronics - Backspin", fileName: "mig - Spintronics - Backspin.avs", collection: "Winamp 5 Picks", url: preset073 },
  { id: "winamp-5-picks/mig - Starslappin", name: "mig - Starslappin", fileName: "mig - Starslappin.avs", collection: "Winamp 5 Picks", url: preset074 },
  { id: "winamp-5-picks/mig - Street Art - Fire Inside", name: "mig - Street Art - Fire Inside", fileName: "mig - Street Art - Fire Inside.avs", collection: "Winamp 5 Picks", url: preset075 },
  { id: "winamp-5-picks/mig - Swoo - Slow", name: "mig - Swoo - Slow", fileName: "mig - Swoo - Slow.avs", collection: "Winamp 5 Picks", url: preset076 },
  { id: "winamp-5-picks/Nic01 - Rototronik", name: "Nic01 - Rototronik", fileName: "Nic01 - Rototronik.avs", collection: "Winamp 5 Picks", url: preset077 },
  { id: "winamp-5-picks/nixa - smell of music (skupers remix)", name: "nixa - smell of music (skupers remix)", fileName: "nixa - smell of music (skupers remix).avs", collection: "Winamp 5 Picks", url: preset078 },
  { id: "winamp-5-picks/p-k - bumpy", name: "p-k - bumpy", fileName: "p-k - bumpy.avs", collection: "Winamp 5 Picks", url: preset079 },
  { id: "winamp-5-picks/S_KuPeRS - ...hidden track...", name: "S_KuPeRS - ...hidden track...", fileName: "S_KuPeRS - ...hidden track....avs", collection: "Winamp 5 Picks", url: preset080 },
  { id: "winamp-5-picks/S_KuPeRS - A Tribute To Degnic", name: "S_KuPeRS - A Tribute To Degnic", fileName: "S_KuPeRS - A Tribute To Degnic.avs", collection: "Winamp 5 Picks", url: preset081 },
  { id: "winamp-5-picks/S_KuPeRS - Arctic Rainbow", name: "S_KuPeRS - Arctic Rainbow", fileName: "S_KuPeRS - Arctic Rainbow.avs", collection: "Winamp 5 Picks", url: preset082 },
  { id: "winamp-5-picks/S_KuPeRS - Chinook", name: "S_KuPeRS - Chinook", fileName: "S_KuPeRS - Chinook.avs", collection: "Winamp 5 Picks", url: preset083 },
  { id: "winamp-5-picks/S_KuPeRS - female demands", name: "S_KuPeRS - female demands", fileName: "S_KuPeRS - female demands.avs", collection: "Winamp 5 Picks", url: preset084 },
  { id: "winamp-5-picks/S_KuPeRS - Hexual Healing", name: "S_KuPeRS - Hexual Healing", fileName: "S_KuPeRS - Hexual Healing.avs", collection: "Winamp 5 Picks", url: preset085 },
  { id: "winamp-5-picks/S_KuPeRS - Inverse Kinetics", name: "S_KuPeRS - Inverse Kinetics", fileName: "S_KuPeRS - Inverse Kinetics.avs", collection: "Winamp 5 Picks", url: preset086 },
  { id: "winamp-5-picks/S_KuPeRS - Kingish", name: "S_KuPeRS - Kingish", fileName: "S_KuPeRS - Kingish.avs", collection: "Winamp 5 Picks", url: preset087 },
  { id: "winamp-5-picks/S_KuPeRS - Spirit Realm (Degnic's Plasmoid RMX)", name: "S_KuPeRS - Spirit Realm (Degnic's Plasmoid RMX)", fileName: "S_KuPeRS - Spirit Realm (Degnic's Plasmoid RMX).avs", collection: "Winamp 5 Picks", url: preset088 },
  { id: "winamp-5-picks/S_KuPeRS - Texering 002", name: "S_KuPeRS - Texering 002", fileName: "S_KuPeRS - Texering 002.avs", collection: "Winamp 5 Picks", url: preset089 },
  { id: "winamp-5-picks/S_KuPeRS - Upward Current", name: "S_KuPeRS - Upward Current", fileName: "S_KuPeRS - Upward Current.avs", collection: "Winamp 5 Picks", url: preset090 },
  { id: "winamp-5-picks/skupers - chinook (exclusive version)", name: "skupers - chinook (exclusive version)", fileName: "skupers - chinook (exclusive version).avs", collection: "Winamp 5 Picks", url: preset091 },
  { id: "winamp-5-picks/splendora", name: "splendora", fileName: "splendora.avs", collection: "Winamp 5 Picks", url: preset092 },
  { id: "winamp-5-picks/Tuggummi - Aqua-fumes", name: "Tuggummi - Aqua-fumes", fileName: "Tuggummi - Aqua-fumes.avs", collection: "Winamp 5 Picks", url: preset093 },
  { id: "winamp-5-picks/Tuggummi - Club Seizure (color enhanced mix)", name: "Tuggummi - Club Seizure (color enhanced mix)", fileName: "Tuggummi - Club Seizure (color enhanced mix).avs", collection: "Winamp 5 Picks", url: preset094 },
  { id: "winamp-5-picks/Tuggummi - Different Load", name: "Tuggummi - Different Load", fileName: "Tuggummi - Different Load.avs", collection: "Winamp 5 Picks", url: preset095 },
  { id: "winamp-5-picks/Tuggummi - Electro blobs", name: "Tuggummi - Electro blobs", fileName: "Tuggummi - Electro blobs.avs", collection: "Winamp 5 Picks", url: preset096 },
  { id: "winamp-5-picks/Tuggummi - Kaleidofied", name: "Tuggummi - Kaleidofied", fileName: "Tuggummi - Kaleidofied.avs", collection: "Winamp 5 Picks", url: preset097 },
  { id: "winamp-5-picks/Tuggummi - Magma Flow II", name: "Tuggummi - Magma Flow II", fileName: "Tuggummi - Magma Flow II.avs", collection: "Winamp 5 Picks", url: preset098 },
  { id: "winamp-5-picks/Tuggummi - Multiple Orgasms", name: "Tuggummi - Multiple Orgasms", fileName: "Tuggummi - Multiple Orgasms.avs", collection: "Winamp 5 Picks", url: preset099 },
  { id: "winamp-5-picks/Tuggummi - Odour Control", name: "Tuggummi - Odour Control", fileName: "Tuggummi - Odour Control.avs", collection: "Winamp 5 Picks", url: preset100 },
  { id: "winamp-5-picks/Tuggummi - Pina Colada", name: "Tuggummi - Pina Colada", fileName: "Tuggummi - Pina Colada.avs", collection: "Winamp 5 Picks", url: preset101 },
  { id: "winamp-5-picks/Tuggummi - Scope in Spotlight II", name: "Tuggummi - Scope in Spotlight II", fileName: "Tuggummi - Scope in Spotlight II.avs", collection: "Winamp 5 Picks", url: preset102 },
  { id: "winamp-5-picks/Tuggummi - Solero Shots", name: "Tuggummi - Solero Shots", fileName: "Tuggummi - Solero Shots.avs", collection: "Winamp 5 Picks", url: preset103 },
  { id: "winamp-5-picks/Tuggummi - Square Minded", name: "Tuggummi - Square Minded", fileName: "Tuggummi - Square Minded.avs", collection: "Winamp 5 Picks", url: preset104 },
  { id: "winamp-5-picks/Tuggummi - Worm-O-Rama (Raz Remix)", name: "Tuggummi - Worm-O-Rama (Raz Remix)", fileName: "Tuggummi - Worm-O-Rama (Raz Remix).avs", collection: "Winamp 5 Picks", url: preset105 },
  { id: "winamp-5-picks/UnConeD -  Zero-G Maze", name: "UnConeD -  Zero-G Maze", fileName: "UnConeD -  Zero-G Maze.avs", collection: "Winamp 5 Picks", url: preset106 },
  { id: "winamp-5-picks/UnConeD - Cartoon Trip", name: "UnConeD - Cartoon Trip", fileName: "UnConeD - Cartoon Trip.avs", collection: "Winamp 5 Picks", url: preset107 },
  { id: "winamp-5-picks/UnConeD - Containment", name: "UnConeD - Containment", fileName: "UnConeD - Containment.avs", collection: "Winamp 5 Picks", url: preset108 },
  { id: "winamp-5-picks/UnConeD - Cubic Flower", name: "UnConeD - Cubic Flower", fileName: "UnConeD - Cubic Flower.avs", collection: "Winamp 5 Picks", url: preset109 },
  { id: "winamp-5-picks/UnConeD - Jello Cube", name: "UnConeD - Jello Cube", fileName: "UnConeD - Jello Cube.avs", collection: "Winamp 5 Picks", url: preset110 },
  { id: "winamp-5-picks/UnConeD - Mercury", name: "UnConeD - Mercury", fileName: "UnConeD - Mercury.avs", collection: "Winamp 5 Picks", url: preset111 },
  { id: "winamp-5-picks/UnConeD - Neon Coaster", name: "UnConeD - Neon Coaster", fileName: "UnConeD - Neon Coaster.avs", collection: "Winamp 5 Picks", url: preset112 },
  { id: "winamp-5-picks/UnConeD - Plankton", name: "UnConeD - Plankton", fileName: "UnConeD - Plankton.avs", collection: "Winamp 5 Picks", url: preset113 },
  { id: "winamp-5-picks/UnConeD - Reflectocube", name: "UnConeD - Reflectocube", fileName: "UnConeD - Reflectocube.avs", collection: "Winamp 5 Picks", url: preset114 },
  { id: "winamp-5-picks/UnConeD - Speeder 3K", name: "UnConeD - Speeder 3K", fileName: "UnConeD - Speeder 3K.avs", collection: "Winamp 5 Picks", url: preset115 },
  { id: "winamp-5-picks/UnConeD - TC Plasma", name: "UnConeD - TC Plasma", fileName: "UnConeD - TC Plasma.avs", collection: "Winamp 5 Picks", url: preset116 },
  { id: "winamp-5-picks/UnConeD - Tie Tunnel SSC", name: "UnConeD - Tie Tunnel SSC", fileName: "UnConeD - Tie Tunnel SSC.avs", collection: "Winamp 5 Picks", url: preset117 },
  { id: "winamp-5-picks/UnConeD - Zero-G Maze II", name: "UnConeD - Zero-G Maze II", fileName: "UnConeD - Zero-G Maze II.avs", collection: "Winamp 5 Picks", url: preset118 },
  { id: "winamp-5-picks/UnConeD -Retrosquares", name: "UnConeD -Retrosquares", fileName: "UnConeD -Retrosquares.avs", collection: "Winamp 5 Picks", url: preset119 },
  { id: "winamp-5-picks/UnConeD -Zero-G Maze III", name: "UnConeD -Zero-G Maze III", fileName: "UnConeD -Zero-G Maze III.avs", collection: "Winamp 5 Picks", url: preset120 },
  { id: "winamp-5-picks/yathosho - fabric (skupers remix)", name: "yathosho - fabric (skupers remix)", fileName: "yathosho - fabric (skupers remix).avs", collection: "Winamp 5 Picks", url: preset121 },
  { id: "winamp-5-picks/Yathosho - microcosm 02", name: "Yathosho - microcosm 02", fileName: "Yathosho - microcosm 02.avs", collection: "Winamp 5 Picks", url: preset122 },
  { id: "winamp-5-picks/zxe-Urantia", name: "zxe-Urantia", fileName: "zxe-Urantia.avs", collection: "Winamp 5 Picks", url: preset123 },
] as const;
